services:
  frontend-main:
    image: nginx:alpine
    container_name: frontend-main
    ports:
      - "8080:80"            # serve MAIN at host:8080
    volumes:
      - /media/dmytrokuzyk/kuato/shared/book-swap-project/frontend/dist-pi-main:/usr/share/nginx/html:ro
    restart: unless-stopped

  frontend-demo:
    image: nginx:alpine
    container_name: frontend-demo
    ports:
      - "8081:80"            # serve DEMO at host:8081
    volumes:
      - /media/dmytrokuzyk/kuato/shared/book-swap-project/frontend/dist-pi-demo:/usr/share/nginx/html:ro
    restart: unless-stopped